[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback agar React Router jalan di refresh/deep-link
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
